
import type { Listing, RoommateProfile } from './types';

export const dummyProperties: Listing[] = [
    {
        id: 'premium-pg-cbd',
        propertyType: 'PG',
        title: 'Premium PG for Professionals',
        rent: 18000,
        area: 150,
        city: 'Navi Mumbai',
        locality: 'CBD Belapur',
        state: 'Maharashtra',
        completeAddress: '101, Elite Residency, Sector 11, CBD Belapur, Navi Mumbai, Maharashtra 400614',
        partialAddress: 'Sector 11, CBD Belapur, Navi Mumbai',
        ownerName: 'Rohan Mehta',
        contactPhone: '+919911223344',
        contactEmail: 'rohan.m@example.com',
        description: 'A premium PG accommodation offering single rooms with all modern amenities. Ideal for working professionals seeking comfort and convenience in CBD Belapur.',
        furnishedStatus: 'Furnished',
        amenities: ['AC', 'WiFi', 'Meals', 'Laundry', 'Housekeeping', 'Security'],
        size: 'Single Room',
        images: [
            'https://placehold.co/600x400',
        ],
        'data-ai-hint': 'modern apartment',
        views: 125,
        ownerId: 'dummyOwner1',
        brokerStatus: 'Without Broker',
        beds: [
            { id: 'bed1', status: 'occupied' },
            { id: 'bed2', status: 'vacant' },
            { id: 'bed3', status: 'vacant' },
            { id: 'bed4', status: 'occupied' },
        ]
    },
    {
        id: 'luxury-2bhk-vashi',
        propertyType: 'Rental',
        title: 'Luxury 2BHK Apartment',
        rent: 45000,
        area: 1200,
        city: 'Navi Mumbai',
        locality: 'Vashi',
        state: 'Maharashtra',
        completeAddress: '205, Ocean Breeze, Sector 17, Vashi, Navi Mumbai, Maharashtra 400703',
        partialAddress: 'Sector 17, Vashi, Navi Mumbai',
        ownerName: 'Smita Patel',
        contactPhone: '+918877665544',
        contactEmail: 'smita.p@example.com',
        description: 'Elegantly designed 2BHK apartment in the heart of Vashi. Features spacious rooms, modern kitchen, and access to all city conveniences.',
        furnishedStatus: 'Furnished',
        amenities: ['AC', 'WiFi', 'Parking', 'Gym', 'Elevator', 'Security'],
        size: '2 BHK',
        images: [
            'https://placehold.co/600x400',
        ],
        'data-ai-hint': 'luxury apartment',
        videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
        views: 340,
        ownerId: 'dummyOwner2',
        brokerStatus: 'With Broker',
    },
    {
        id: 'spacious-3bhk-kharghar',
        propertyType: 'Rental',
        title: 'Spacious 3BHK House with Garden',
        rent: 35000,
        area: 1800,
        city: 'Navi Mumbai',
        locality: 'Kharghar',
        state: 'Maharashtra',
        completeAddress: 'Villa 7, Green Enclave, Sector 10, Kharghar, Navi Mumbai, Maharashtra 410210',
        partialAddress: 'Sector 10, Kharghar, Navi Mumbai',
        ownerName: 'Vikas Rao',
        contactPhone: '+917766554433',
        contactEmail: 'vikas.r@example.com',
        description: 'A beautiful 3BHK independent house with a lush garden. Perfect for families, located in a peaceful and green locality.',
        furnishedStatus: 'Semi-Furnished',
        amenities: ['Parking', 'Balcony', 'Garden', 'Power Backup'],
        size: '3 BHK',
        images: [
            'https://placehold.co/600x400',
        ],
        'data-ai-hint': 'house garden',
        views: 210,
        ownerId: 'dummyOwner1',
        brokerStatus: 'Without Broker',
    },
    {
        id: 'modern-2bhk-nerul',
        propertyType: 'Rental',
        title: 'Modern 2BHK in Nerul',
        rent: 30000,
        area: 1100,
        city: 'Navi Mumbai',
        locality: 'Nerul',
        state: 'Maharashtra',
        completeAddress: 'B-501, Tech Residency, Sector 20, Nerul, Navi Mumbai, Maharashtra 400706',
        partialAddress: 'Sector 20, Nerul, Navi Mumbai',
        ownerName: 'Anil Kumar',
        contactPhone: '+919988776655',
        contactEmail: 'anil.k@example.com',
        description: 'Bright and airy 2BHK, walking distance to major tech parks. Features a spacious living area and modern kitchen appliances.',
        furnishedStatus: 'Furnished',
        amenities: ['AC', 'WiFi', 'Gym', 'Elevator'],
        size: '2 BHK',
        images: [
            'https://placehold.co/600x400',
        ],
        'data-ai-hint': 'bright apartment',
        views: 95,
        ownerId: 'dummyOwner3',
        brokerStatus: 'With Broker',
    },
];

export const dummyRoommates: RoommateProfile[] = [
    {
        id: 'rahul-sharma-belapur',
        propertyType: 'Roommate',
        ownerName: 'Rahul Sharma',
        age: 28,
        rent: 20000,
        city: 'Navi Mumbai',
        locality: 'CBD Belapur',
        state: 'Maharashtra',
        completeAddress: 'Seeking a 2BHK in CBD Belapur, Navi Mumbai, Maharashtra',
        partialAddress: 'CBD Belapur, Navi Mumbai',
        contactPhone: '+919012345678',
        contactEmail: 'rahul.sharma@example.com',
        description: 'Friendly and organized software engineer looking for a male roommate to find and share an apartment with. Prefer a non-smoker, clean and quiet environment.',
        preferences: ['Non-Smoker', 'Clean', 'Drinker', 'Vegetarian'],
        gender: 'Male',
        images: [
            'https://placehold.co/400x400',
        ],
        'data-ai-hint': 'male portrait',
        views: 75,
        ownerId: 'dummyRoommateOwner1',
        hasProperty: false,
    },
    {
        id: 'ankita-reddy-kharghar',
        propertyType: 'Roommate',
        ownerName: 'Ankita Reddy',
        age: 26,
        rent: 18000,
        city: 'Navi Mumbai',
        locality: 'Kharghar',
        state: 'Maharashtra',
        completeAddress: 'Seeking female roommate in Kharghar, Navi Mumbai, Maharashtra',
        partialAddress: 'Kharghar, Navi Mumbai',
        contactPhone: '+918012345678',
        contactEmail: 'ankita.r@example.com',
        description: "I have a lovely 2BHK and am looking for a female roommate to share it. I enjoy cooking and quiet evenings. Prefer someone clean and respectful.",
        preferences: ['Non-Smoker', 'Clean', 'Drinker', 'Non-Vegetarian'],
        gender: 'Female',
        images: [
            'https://placehold.co/400x400',
        ],
        'data-ai-hint': 'female portrait',
        views: 180,
        ownerId: 'dummyRoommateOwner2',
        hasProperty: true,
    },
];
